server:
  port: 80

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/note
    password: 123456

  jpa:
    generate-ddl: true

logging:
  level:
    org:
      springframeword:
        security:
          info